/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.probestack.sdk.model.CreateOrderRequestItemsInner;
import com.probestack.sdk.model.CreateOrderRequestShippingAddress;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateOrderRequest
 */
@JsonPropertyOrder({
  CreateOrderRequest.JSON_PROPERTY_CUSTOMER_ID,
  CreateOrderRequest.JSON_PROPERTY_ITEMS,
  CreateOrderRequest.JSON_PROPERTY_SHIPPING_ADDRESS,
  CreateOrderRequest.JSON_PROPERTY_COUPON_CODE
})
@JsonTypeName("createOrder_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-18T07:34:32.000683723Z[GMT]", comments = "Generator version: 7.9.0")
public class CreateOrderRequest {
  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
  private String customerId;

  public static final String JSON_PROPERTY_ITEMS = "items";
  private List<CreateOrderRequestItemsInner> items = new ArrayList<>();

  public static final String JSON_PROPERTY_SHIPPING_ADDRESS = "shippingAddress";
  private CreateOrderRequestShippingAddress shippingAddress;

  public static final String JSON_PROPERTY_COUPON_CODE = "couponCode";
  private String couponCode;

  public CreateOrderRequest() {
  }

  public CreateOrderRequest customerId(String customerId) {
    
    this.customerId = customerId;
    return this;
  }

  /**
   * ID of the customer placing the order
   * @return customerId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCustomerId() {
    return customerId;
  }


  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public CreateOrderRequest items(List<CreateOrderRequestItemsInner> items) {
    
    this.items = items;
    return this;
  }

  public CreateOrderRequest addItemsItem(CreateOrderRequestItemsInner itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

  /**
   * Line items in this order
   * @return items
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<CreateOrderRequestItemsInner> getItems() {
    return items;
  }


  @JsonProperty(JSON_PROPERTY_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setItems(List<CreateOrderRequestItemsInner> items) {
    this.items = items;
  }

  public CreateOrderRequest shippingAddress(CreateOrderRequestShippingAddress shippingAddress) {
    
    this.shippingAddress = shippingAddress;
    return this;
  }

  /**
   * Get shippingAddress
   * @return shippingAddress
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public CreateOrderRequestShippingAddress getShippingAddress() {
    return shippingAddress;
  }


  @JsonProperty(JSON_PROPERTY_SHIPPING_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShippingAddress(CreateOrderRequestShippingAddress shippingAddress) {
    this.shippingAddress = shippingAddress;
  }

  public CreateOrderRequest couponCode(String couponCode) {
    
    this.couponCode = couponCode;
    return this;
  }

  /**
   * Optional discount coupon to apply
   * @return couponCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUPON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCouponCode() {
    return couponCode;
  }


  @JsonProperty(JSON_PROPERTY_COUPON_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderRequest createOrderRequest = (CreateOrderRequest) o;
    return Objects.equals(this.customerId, createOrderRequest.customerId) &&
        Objects.equals(this.items, createOrderRequest.items) &&
        Objects.equals(this.shippingAddress, createOrderRequest.shippingAddress) &&
        Objects.equals(this.couponCode, createOrderRequest.couponCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customerId, items, shippingAddress, couponCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderRequest {\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

