/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * CreateOrderRequestItemsInner
 */
@JsonPropertyOrder({
  CreateOrderRequestItemsInner.JSON_PROPERTY_PRODUCT_ID,
  CreateOrderRequestItemsInner.JSON_PROPERTY_QUANTITY,
  CreateOrderRequestItemsInner.JSON_PROPERTY_UNIT_PRICE_CENTS
})
@JsonTypeName("createOrder_request_items_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-06T06:06:32.426875943Z[GMT]", comments = "Generator version: 7.9.0")
public class CreateOrderRequestItemsInner {
  public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
  private String productId;

  public static final String JSON_PROPERTY_QUANTITY = "quantity";
  private Integer quantity;

  public static final String JSON_PROPERTY_UNIT_PRICE_CENTS = "unitPriceCents";
  private Integer unitPriceCents;

  public CreateOrderRequestItemsInner() {
  }

  public CreateOrderRequestItemsInner productId(String productId) {
    
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProductId(String productId) {
    this.productId = productId;
  }

  public CreateOrderRequestItemsInner quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

  /**
   * Get quantity
   * @return quantity
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getQuantity() {
    return quantity;
  }


  @JsonProperty(JSON_PROPERTY_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public CreateOrderRequestItemsInner unitPriceCents(Integer unitPriceCents) {
    
    this.unitPriceCents = unitPriceCents;
    return this;
  }

  /**
   * Get unitPriceCents
   * @return unitPriceCents
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UNIT_PRICE_CENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUnitPriceCents() {
    return unitPriceCents;
  }


  @JsonProperty(JSON_PROPERTY_UNIT_PRICE_CENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUnitPriceCents(Integer unitPriceCents) {
    this.unitPriceCents = unitPriceCents;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateOrderRequestItemsInner createOrderRequestItemsInner = (CreateOrderRequestItemsInner) o;
    return Objects.equals(this.productId, createOrderRequestItemsInner.productId) &&
        Objects.equals(this.quantity, createOrderRequestItemsInner.quantity) &&
        Objects.equals(this.unitPriceCents, createOrderRequestItemsInner.unitPriceCents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, quantity, unitPriceCents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateOrderRequestItemsInner {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    unitPriceCents: ").append(toIndentedString(unitPriceCents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

