/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InventoryLevel
 */
@JsonPropertyOrder({
  InventoryLevel.JSON_PROPERTY_PRODUCT_ID,
  InventoryLevel.JSON_PROPERTY_AVAILABLE_QUANTITY,
  InventoryLevel.JSON_PROPERTY_WAREHOUSE_COUNT,
  InventoryLevel.JSON_PROPERTY_LAST_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-06T06:06:32.426875943Z[GMT]", comments = "Generator version: 7.9.0")
public class InventoryLevel {
  public static final String JSON_PROPERTY_PRODUCT_ID = "productId";
  private String productId;

  public static final String JSON_PROPERTY_AVAILABLE_QUANTITY = "availableQuantity";
  private Integer availableQuantity;

  public static final String JSON_PROPERTY_WAREHOUSE_COUNT = "warehouseCount";
  private Integer warehouseCount;

  public static final String JSON_PROPERTY_LAST_UPDATED_AT = "lastUpdatedAt";
  private OffsetDateTime lastUpdatedAt;

  public InventoryLevel() {
  }

  public InventoryLevel productId(String productId) {
    
    this.productId = productId;
    return this;
  }

  /**
   * Get productId
   * @return productId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getProductId() {
    return productId;
  }


  @JsonProperty(JSON_PROPERTY_PRODUCT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductId(String productId) {
    this.productId = productId;
  }

  public InventoryLevel availableQuantity(Integer availableQuantity) {
    
    this.availableQuantity = availableQuantity;
    return this;
  }

  /**
   * Get availableQuantity
   * @return availableQuantity
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AVAILABLE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAvailableQuantity() {
    return availableQuantity;
  }


  @JsonProperty(JSON_PROPERTY_AVAILABLE_QUANTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableQuantity(Integer availableQuantity) {
    this.availableQuantity = availableQuantity;
  }

  public InventoryLevel warehouseCount(Integer warehouseCount) {
    
    this.warehouseCount = warehouseCount;
    return this;
  }

  /**
   * Get warehouseCount
   * @return warehouseCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WAREHOUSE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getWarehouseCount() {
    return warehouseCount;
  }


  @JsonProperty(JSON_PROPERTY_WAREHOUSE_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarehouseCount(Integer warehouseCount) {
    this.warehouseCount = warehouseCount;
  }

  public InventoryLevel lastUpdatedAt(OffsetDateTime lastUpdatedAt) {
    
    this.lastUpdatedAt = lastUpdatedAt;
    return this;
  }

  /**
   * Get lastUpdatedAt
   * @return lastUpdatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastUpdatedAt() {
    return lastUpdatedAt;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdatedAt(OffsetDateTime lastUpdatedAt) {
    this.lastUpdatedAt = lastUpdatedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InventoryLevel inventoryLevel = (InventoryLevel) o;
    return Objects.equals(this.productId, inventoryLevel.productId) &&
        Objects.equals(this.availableQuantity, inventoryLevel.availableQuantity) &&
        Objects.equals(this.warehouseCount, inventoryLevel.warehouseCount) &&
        Objects.equals(this.lastUpdatedAt, inventoryLevel.lastUpdatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, availableQuantity, warehouseCount, lastUpdatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryLevel {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    availableQuantity: ").append(toIndentedString(availableQuantity)).append("\n");
    sb.append("    warehouseCount: ").append(toIndentedString(warehouseCount)).append("\n");
    sb.append("    lastUpdatedAt: ").append(toIndentedString(lastUpdatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

