/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RefundOrderRequest
 */
@JsonPropertyOrder({
  RefundOrderRequest.JSON_PROPERTY_AMOUNT_CENTS,
  RefundOrderRequest.JSON_PROPERTY_REASON,
  RefundOrderRequest.JSON_PROPERTY_NOTIFY_CUSTOMER
})
@JsonTypeName("refundOrder_request")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-06T06:06:32.426875943Z[GMT]", comments = "Generator version: 7.9.0")
public class RefundOrderRequest {
  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amountCents";
  private Integer amountCents;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_NOTIFY_CUSTOMER = "notifyCustomer";
  private Boolean notifyCustomer;

  public RefundOrderRequest() {
  }

  public RefundOrderRequest amountCents(Integer amountCents) {
    
    this.amountCents = amountCents;
    return this;
  }

  /**
   * Amount to refund, in cents
   * @return amountCents
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getAmountCents() {
    return amountCents;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmountCents(Integer amountCents) {
    this.amountCents = amountCents;
  }

  public RefundOrderRequest reason(String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Reason for the refund
   * @return reason
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReason(String reason) {
    this.reason = reason;
  }

  public RefundOrderRequest notifyCustomer(Boolean notifyCustomer) {
    
    this.notifyCustomer = notifyCustomer;
    return this;
  }

  /**
   * Whether to email the customer about this refund
   * @return notifyCustomer
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NOTIFY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getNotifyCustomer() {
    return notifyCustomer;
  }


  @JsonProperty(JSON_PROPERTY_NOTIFY_CUSTOMER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotifyCustomer(Boolean notifyCustomer) {
    this.notifyCustomer = notifyCustomer;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundOrderRequest refundOrderRequest = (RefundOrderRequest) o;
    return Objects.equals(this.amountCents, refundOrderRequest.amountCents) &&
        Objects.equals(this.reason, refundOrderRequest.reason) &&
        Objects.equals(this.notifyCustomer, refundOrderRequest.notifyCustomer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountCents, reason, notifyCustomer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundOrderRequest {\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    notifyCustomer: ").append(toIndentedString(notifyCustomer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

