/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RefundResult
 */
@JsonPropertyOrder({
  RefundResult.JSON_PROPERTY_ORDER_ID,
  RefundResult.JSON_PROPERTY_AMOUNT_CENTS,
  RefundResult.JSON_PROPERTY_REASON,
  RefundResult.JSON_PROPERTY_REFUNDED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-10-06T06:06:32.426875943Z[GMT]", comments = "Generator version: 7.9.0")
public class RefundResult {
  public static final String JSON_PROPERTY_ORDER_ID = "orderId";
  private String orderId;

  public static final String JSON_PROPERTY_AMOUNT_CENTS = "amountCents";
  private Integer amountCents;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_REFUNDED_AT = "refundedAt";
  private OffsetDateTime refundedAt;

  public RefundResult() {
  }

  public RefundResult orderId(String orderId) {
    
    this.orderId = orderId;
    return this;
  }

  /**
   * Get orderId
   * @return orderId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOrderId() {
    return orderId;
  }


  @JsonProperty(JSON_PROPERTY_ORDER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public RefundResult amountCents(Integer amountCents) {
    
    this.amountCents = amountCents;
    return this;
  }

  /**
   * Get amountCents
   * @return amountCents
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAmountCents() {
    return amountCents;
  }


  @JsonProperty(JSON_PROPERTY_AMOUNT_CENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAmountCents(Integer amountCents) {
    this.amountCents = amountCents;
  }

  public RefundResult reason(String reason) {
    
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(String reason) {
    this.reason = reason;
  }

  public RefundResult refundedAt(OffsetDateTime refundedAt) {
    
    this.refundedAt = refundedAt;
    return this;
  }

  /**
   * Get refundedAt
   * @return refundedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REFUNDED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getRefundedAt() {
    return refundedAt;
  }


  @JsonProperty(JSON_PROPERTY_REFUNDED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefundedAt(OffsetDateTime refundedAt) {
    this.refundedAt = refundedAt;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RefundResult refundResult = (RefundResult) o;
    return Objects.equals(this.orderId, refundResult.orderId) &&
        Objects.equals(this.amountCents, refundResult.amountCents) &&
        Objects.equals(this.reason, refundResult.reason) &&
        Objects.equals(this.refundedAt, refundResult.refundedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(orderId, amountCents, reason, refundedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RefundResult {\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    amountCents: ").append(toIndentedString(amountCents)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    refundedAt: ").append(toIndentedString(refundedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

