/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.api;

import com.probestack.sdk.model.CancelOrderRequest;
import com.probestack.sdk.model.CreateOrderRequest;
import com.probestack.sdk.model.InventoryLevel;
import com.probestack.sdk.model.Order;
import com.probestack.sdk.model.RefundOrderRequest;
import com.probestack.sdk.model.RefundResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.web.client.RestClientException;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
@Disabled
class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * Cancel an order
     *
     * Cancels an order that has not yet shipped.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void cancelOrderTest() {
        String orderId = null;
        CancelOrderRequest cancelOrderRequest = null;

        Order response = api.cancelOrder(orderId, cancelOrderRequest);

        // TODO: test validations
    }
    
    /**
     * Create a new order
     *
     * Places a new order for a customer with one or more line items and a shipping address.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void createOrderTest() {
        CreateOrderRequest createOrderRequest = null;

        Order response = api.createOrder(createOrderRequest);

        // TODO: test validations
    }
    
    /**
     * Get an order by ID
     *
     * Retrieves full order details including line items and totals.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getOrderByIdTest() {
        String orderId = null;

        Order response = api.getOrderById(orderId);

        // TODO: test validations
    }
    
    /**
     * Check a product&#39;s current stock level
     *
     * Returns the current available quantity for a product across all warehouses.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void getProductInventoryTest() {
        String productId = null;

        InventoryLevel response = api.getProductInventory(productId);

        // TODO: test validations
    }
    
    /**
     * List orders
     *
     * Returns orders, optionally filtered by status or customer.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void listOrdersTest() {
        String status = null;
        String customerId = null;
        Integer limit = null;

        List<Order> response = api.listOrders(status, customerId, limit);

        // TODO: test validations
    }
    
    /**
     * Refund an order (fully or partially)
     *
     * Issues a refund for all or part of a paid order&#39;s total.
     *
     * @throws RestClientException
     *          if the Api call fails
     */
    @Test
    void refundOrderTest() {
        String orderId = null;
        RefundOrderRequest refundOrderRequest = null;

        RefundResult response = api.refundOrder(orderId, refundOrderRequest);

        // TODO: test validations
    }
    
}
