/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.probestack.sdk.model.CreateOrderRequestItemsInner;
import com.probestack.sdk.model.CreateOrderRequestShippingAddress;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateOrderRequest
 */
class CreateOrderRequestTest {
    private final CreateOrderRequest model = new CreateOrderRequest();

    /**
     * Model tests for CreateOrderRequest
     */
    @Test
    void testCreateOrderRequest() {
        // TODO: test CreateOrderRequest
    }

    /**
     * Test the property 'customerId'
     */
    @Test
    void customerIdTest() {
        // TODO: test customerId
    }

    /**
     * Test the property 'items'
     */
    @Test
    void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'shippingAddress'
     */
    @Test
    void shippingAddressTest() {
        // TODO: test shippingAddress
    }

    /**
     * Test the property 'couponCode'
     */
    @Test
    void couponCodeTest() {
        // TODO: test couponCode
    }

}
