/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateOrderRequestShippingAddress
 */
class CreateOrderRequestShippingAddressTest {
    private final CreateOrderRequestShippingAddress model = new CreateOrderRequestShippingAddress();

    /**
     * Model tests for CreateOrderRequestShippingAddress
     */
    @Test
    void testCreateOrderRequestShippingAddress() {
        // TODO: test CreateOrderRequestShippingAddress
    }

    /**
     * Test the property 'line1'
     */
    @Test
    void line1Test() {
        // TODO: test line1
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

}
