/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for InventoryLevel
 */
class InventoryLevelTest {
    private final InventoryLevel model = new InventoryLevel();

    /**
     * Model tests for InventoryLevel
     */
    @Test
    void testInventoryLevel() {
        // TODO: test InventoryLevel
    }

    /**
     * Test the property 'productId'
     */
    @Test
    void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'availableQuantity'
     */
    @Test
    void availableQuantityTest() {
        // TODO: test availableQuantity
    }

    /**
     * Test the property 'warehouseCount'
     */
    @Test
    void warehouseCountTest() {
        // TODO: test warehouseCount
    }

    /**
     * Test the property 'lastUpdatedAt'
     */
    @Test
    void lastUpdatedAtTest() {
        // TODO: test lastUpdatedAt
    }

}
