/*
 * Order Management API
 * An e-commerce order management API — heavier on numeric/currency fields and array-of-object request bodies (line items) than the other three example specs, to exercise mock-data generation and negative/boundary test scenarios differently (amounts, quantities, nested item arrays). 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.probestack.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RefundOrderRequest
 */
class RefundOrderRequestTest {
    private final RefundOrderRequest model = new RefundOrderRequest();

    /**
     * Model tests for RefundOrderRequest
     */
    @Test
    void testRefundOrderRequest() {
        // TODO: test RefundOrderRequest
    }

    /**
     * Test the property 'amountCents'
     */
    @Test
    void amountCentsTest() {
        // TODO: test amountCents
    }

    /**
     * Test the property 'reason'
     */
    @Test
    void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'notifyCustomer'
     */
    @Test
    void notifyCustomerTest() {
        // TODO: test notifyCustomer
    }

}
